[package]
name = "rust-first-steps"
version = "0.1.0"
edition = "2021"
authors = ["Ever Ruiz Diaz <ruizdiaz.oe@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
